services:
  mysql:
    image: mysql:8.3.0
    container_name: food_delivery_mysql
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: food_delivery
    volumes:
      - ./mysql:/var/lib/mysql
      - .docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:alpine
    container_name: food_delivery_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data